name: 'laravel-one-generate'
description: 'Action to generate static web pages'
branding:
  icon: 'file'
  color: 'blue'
inputs:
  url:
    description: 'The base URL of the website'
    required: true
  php-version:
    description: 'PHP version to use (supports 8.0 and above)'
    required: false
    default: '8.3'
    pattern: '^8\.[0-9]+$'
runs:
  using: "composite"
  steps:

    - name: Initialize PHP ${{env.PHP_VERSION}}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{env.PHP_VERSION}}
        tools: abenevaut/laravel-one
      env:
        PHP_VERSION: ${{ inputs.php-version }}

    - name: Generate static pages
      run: laravel-one generate ${{env.URL}}
      shell: bash
      env:
        URL: ${{ inputs.url }}
