name: laravel-one-ghpages

on:
  release:
    types: [ created ]

env:
  php_version: 8.1

jobs:

  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/heads/master')
    concurrency:
      group: laravel-one-ghpages-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    steps:

      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize PHP ${{ env.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}

      - name: Configure Composer cache
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-node-php_${{ env.php_version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-node-php_${{ env.php_version }}-

      - name: Composer install
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install -o --no-interaction --prefer-dist

      - name: Web pages cache
        id: web-pages-cache
        uses: actions/cache@v2
        with:
          path: .cache
          key: ${{ runner.os }}-pages-cache-php_${{ env.php_version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-pages-cache-php_${{ env.php_version }}-${{ hashFiles('**/composer.json') }}

      - name: Generate static pages
        run: php laravel-one generate https://laravel-one.abenevaut.dev

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ABENEVAUT_GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
